ITDeviceManagement/Models/Device.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ITDeviceManagement.Models
{
    public class Device
    {
        public int ID { get; set; }
        public string DeviceName { get; set; }
        public int DeviceCategoryID { get; set; }
        public DateTime? AcquisitionDate { get; set; }
        public string Memo { get; set; }

        // Navigation properties
        public DeviceCategory DeviceCategory { get; set; }
        public ICollection<DeviceProperty> DeviceProperties { get; set; }
    }

}

ITDeviceManagement/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITDeviceManagement.Models;

namespace ITDeviceManagement.Controllers
{
    public class DevicesController : Controller
    {
        private ITInventoryDBContext db = new ITInventoryDBContext();

        /// GET: Devices
        public async Task<ActionResult> Index()
        {
            var devices = db.Devices
                            .Include(d => d.DeviceCategory)
                            .Include(d => d.DeviceProperties.Select(dp => dp.Property)); // Include related properties
            return View(await devices.ToListAsync());
        }


        // GET: Devices/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = await db.Devices.FindAsync(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        public ActionResult Create()
        {
            // Populate the dropdown list with device categories
            ViewBag.DeviceCategoryID = new SelectList(db.DeviceCategories, "ID", "CategoryName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DeviceName,DeviceCategoryID,AcquisitionDate,Memo")] Device device, List<DeviceProperty> deviceProperties)
        {
            if (ModelState.IsValid)
            {
                // Add the new device to the database
                db.Devices.Add(device);
                db.SaveChanges();

                // Save the properties associated with this device
                foreach (var prop in deviceProperties)
                {
                    prop.DeviceID = device.ID;
                    db.DeviceProperties.Add(prop);
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            // If we got this far, something failed; re-populate the dropdown list
            ViewBag.DeviceCategoryID = new SelectList(db.DeviceCategories, "ID", "CategoryName", device.DeviceCategoryID);
            return View(device);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(int id)
        {
            // Include the related DeviceProperties and their associated Property details
            var device = db.Devices
                           .Include(d => d.DeviceProperties.Select(dp => dp.Property))
                           .FirstOrDefault(d => d.ID == id);

            if (device == null)
            {
                return HttpNotFound();
            }

            ViewBag.DeviceCategoryID = new SelectList(db.DeviceCategories, "ID", "CategoryName", device.DeviceCategoryID);
            return View(device);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Device model, List<DeviceProperty> deviceProperties)
        {
            if (ModelState.IsValid)
            {
                // Load the existing device from the database
                var device = db.Devices.Include(d => d.DeviceProperties)
                                       .SingleOrDefault(d => d.ID == model.ID);

                if (device == null)
                {
                    return HttpNotFound();
                }

                // Update device details
                device.DeviceName = model.DeviceName;
                device.DeviceCategoryID = model.DeviceCategoryID;
                device.AcquisitionDate = model.AcquisitionDate;
                device.Memo = model.Memo;

                // Remove old properties
                db.DeviceProperties.RemoveRange(device.DeviceProperties);

                // Add new properties
                foreach (var prop in deviceProperties)
                {
                    if (!string.IsNullOrEmpty(prop.PropertyValue))
                    {
                        db.DeviceProperties.Add(new DeviceProperty
                        {
                            DeviceID = device.ID,
                            PropertyID = prop.PropertyID,
                            PropertyValue = prop.PropertyValue
                        });
                    }
                }

                // Save changes
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            // Reload categories for the view
            ViewBag.DeviceCategoryID = new SelectList(db.DeviceCategories, "ID", "CategoryName", model.DeviceCategoryID);
            return View(model);
        }

        // GET: Devices/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = await db.Devices.FindAsync(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Device device = await db.Devices.FindAsync(id);
            db.Devices.Remove(device);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public JsonResult GetPropertiesByCategory(int categoryId)
        {
            // Retrieve the properties associated with the selected device category
            var properties = (from p in db.Properties
                              join cp in db.DeviceCategoryProperties on p.ID equals cp.PropertyID
                              where cp.DeviceCategoryID == categoryId
                              select new
                              {
                                  p.ID,
                                  p.PropertyDescription
                              }).ToList();

            return Json(properties, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITDeviceManagement/Views/Devices/Create.cshtml
@model ITDeviceManagement.Models.Device

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Device</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!-- Device Name -->
        <div class="form-group">
            @Html.LabelFor(model => model.DeviceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Device Category -->
        <div class="form-group">
            @Html.LabelFor(model => model.DeviceCategoryID, "Device Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DeviceCategoryID", (SelectList)ViewBag.DeviceCategoryID, "Select a Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeviceCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Acquisition Date -->
        <div class="form-group">
            @Html.LabelFor(model => model.AcquisitionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AcquisitionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AcquisitionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Memo -->
        <div class="form-group">
            @Html.LabelFor(model => model.Memo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Memo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Memo, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Dynamic Properties Section -->
        <div id="propertiesSection">
            <!-- Properties will be loaded here dynamically -->
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
    $(document).ready(function() {
        $('#DeviceCategoryID').change(function() {
            var categoryId = $(this).val();
            if (categoryId) {
                $.ajax({
                    url: '@Url.Action("GetPropertiesByCategory", "Devices")',
                    type: 'GET',
                    data: { categoryId: categoryId },
                    success: function(data) {
                        $('#propertiesSection').empty(); // Clear previous properties
                        $.each(data, function(index, property) {
                            $('#propertiesSection').append(
                                '<div class="form-group">' +
                                '<label class="control-label col-md-2">' + property.PropertyDescription + '</label>' +
                                '<div class="col-md-10">' +
                                '<input type="text" name="DeviceProperties[' + index + '].PropertyValue" class="form-control" />' +
                                '<input type="hidden" name="DeviceProperties[' + index + '].PropertyID" value="' + property.ID + '" />' +
                                '</div>' +
                                '</div>'
                            );
                        });
                    },
                    error: function(xhr, status, error) {
                        console.log("AJAX error: " + status + ' - ' + error);
                    }
                });
            } else {
                $('#propertiesSection').empty(); // Clear properties if no category is selected
            }
        });
    });
    </script>

}

ITDeviceManagement/Views/Devices/Delete.cshtml
@model ITDeviceManagement.Models.Device

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeviceCategory.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceCategory.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcquisitionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcquisitionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ITDeviceManagement/Views/Devices/Details.cshtml
@model ITDeviceManagement.Models.Device

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeviceCategory.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceCategory.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcquisitionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcquisitionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ITDeviceManagement/Views/Devices/Edit.cshtml
@model ITDeviceManagement.Models.Device

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Device</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ID)

        <!-- Device Name Section -->
        <div class="form-group">
            @Html.LabelFor(model => model.DeviceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Device Category Section -->
        <div class="form-group">
            @Html.LabelFor(model => model.DeviceCategoryID, "Device Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DeviceCategoryID", (SelectList)ViewBag.DeviceCategoryID, htmlAttributes: new { @class = "form-control", id = "deviceCategory", @disabled = "disabled" })
                @Html.HiddenFor(model => model.DeviceCategoryID) <!-- Hidden field to ensure the category ID is still submitted -->
                @Html.ValidationMessageFor(model => model.DeviceCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Acquisition Date Section -->
        <div class="form-group">
            @Html.LabelFor(model => model.AcquisitionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AcquisitionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AcquisitionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Memo Section -->
        <div class="form-group">
            @Html.LabelFor(model => model.Memo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Memo, new { @class = "form-control", rows = 3 })
                @Html.ValidationMessageFor(model => model.Memo, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Properties Section -->
        <h4>Properties</h4>
        <hr />
        <div id="propertiesContainer">
            @if (Model.DeviceProperties != null && Model.DeviceProperties.Any())
            {
                int index = 0;
                foreach (var deviceProperty in Model.DeviceProperties)
                {
                    <div class="form-group">
                        @Html.Label(deviceProperty.Property.PropertyDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.Hidden($"DeviceProperties[{index}].PropertyID", deviceProperty.PropertyID)
                            @Html.TextBox($"DeviceProperties[{index}].PropertyValue", deviceProperty.PropertyValue, new { @class = "form-control" })
                        </div>
                    </div>
                    index++;
                }
            }
        </div>

        <!-- Submit Button -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITDeviceManagement/Views/Devices/Index.cshtml
@model IEnumerable<ITDeviceManagement.Models.Device>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DeviceCategory.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeviceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AcquisitionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Memo)
        </th>
        <th>Properties</th> <!-- Add a header for properties -->
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DeviceCategory.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeviceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcquisitionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memo)
            </td>
            <td>
                <ul>
                    @foreach (var prop in item.DeviceProperties)
                    {
                        <li>@prop.Property.PropertyDescription: @prop.PropertyValue</li>
                    }
                </ul>
            </td> <!-- Display each property -->
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>